# in the future, this should be more equivalent to production setup instead of dev setup

services:
  node_backend:
    command: >
      sh -c "pnpm run db:2migrate_apply &&
            pnpm run db:3typegen &&
            npx vitest run"
