services:
  node_backend:
    build:
      context: .
      dockerfile: node_backend/Dockerfile
    container_name: node_backend
    env_file:
      - ./node_backend/.env
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./node_backend:/app # Mount the local backend code into the container (for live reload in dev)
      - /app/node_modules
    command: >
      sh -c "pnpm run db:2migrate_apply &&
            pnpm run db:3typegen &&
            npx vitest run"
    depends_on:
      - postgres # Ensure that PostgreSQL starts first

  postgres:
    image: postgres:17.2
    container_name: postgres
    env_file:
      - ./node_backend/.env
    ports:
      - "5432:5432" # Expose PostgreSQL on port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data on host

volumes:
  postgres_data: # Named volume for PostgreSQL data persistence
