name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      docker:
        image: docker:dind # Docker-in-Docker
        options: --privileged

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose and run tests
        run: docker compose -f docker-compose.yml -f docker-compose.ga.autotest.yml up --build --abort-on-container-exit

      - name: Run ESLint in node_backend container
        run: docker compose run --rm node_backend pnpm run lint

      - name: Stop Docker Containers
        run: docker compose down -v
