name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind # Docker-in-Docker
        options: --privileged

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose up --build

      - name: Wait for Backend to be Ready
        run: |
          echo "Waiting for backend to be available..."
          until curl -sSf http://localhost:3000/ > /dev/null; do
            echo "Backend not ready yet..."
            sleep 2
          done
          echo "Backend is up!"

      - name: Run Tests for node_backend container
        run: docker compose exec -T node_backend npx vitest run

      - name: Stop Docker Containers
        run: docker compose down -v
