name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind # Docker-in-Docker
        options: --privileged

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Environment Variables
        run: |
          echo "PORT=3000" > node_backend/.env
          echo "NODE_ENV=development" >> node_backend/.env
          echo "POSTGRES_USER=postgres" >> node_backend/.env
          echo "POSTGRES_PASSWORD=postgres" >> node_backend/.env
          echo "POSTGRES_DB=mydb" >> node_backend/.env
          echo "DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}" >> node_backend/.env

      - name: Set up Docker Compose
        run: docker compose up -d --build
        env:
          DB_HOST: localhost
          DB_USER: root
          DB_PASSWORD: secret

      - name: Run Tests Inside Container
        run: docker-compose exec -T app pnpm test

      - name: Stop Docker Containers
        run: docker-compose down
